# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1582be6ea29904817b14c37e2625f3b9c55da15a357e6a06981b3fa778aca6638a94186874033592fa2129bcb58e2e4f4ba3583b9654010a4920ae1220c89d37

test:
  secret_key_base: e8bdbfa944412cd40d346a91e7f95c5e0a6752efa290294c49ef8202dac0d902ce1bd28e9cfa8de79404acff610c2d6e60abea8cbec2a54316870361c5d83e04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
